consumer_key = 'PUT YOUR CONSUMER KEY HERE'
consumer_secret = 'DITTO'
oauth_token = 'I BELIEVE THE VARIABLE NAMES ARE PRETTY SELF EXPLANATORY'
oauth_secret = 'HOWEVER, AT THIS MOMENT, ONLY CONSUMER_KEY IS REQUIRED. I APOLOGIZE FOR YELLING'

api_key = consumer_key
